export const SPORTS = [
  "Athlétisme",
  "Aviron",
  "Badminton",
  "Baseball",
  "Basketball",
  "Boxe",
  "Canoë-kayak",
  "Cricket",
  "Cyclisme",
  "Danse",
  "Escalade",
  "Escrime",
  "Football",
  "Football américain",
  "Golf",
  "Gymnastique",
  "Handball",
  "Hockey sur gazon",
  "Hockey sur glace",
  "Judo",
  "Karaté",
  "Lutte",
  "Natation",
  "Pétanque",
  "Plongée",
  "Rugby",
  "Skateboard",
  "Ski",
  "Snowboard",
  "Surf",
  "Taekwondo",
  "Tennis",
  "Tennis de table",
  "Tir à l'arc",
  "Triathlon",
  "Volleyball",
  "VTT",
  "Autre",
] as const;
